<?php

/**
 * @file
 *   Drupal user and Drupal VoIP module integration.
 */

define('VOIPUSERNUMBER_CONFIRMED', 0x0001);
define('VOIPUSERNUMBER_ACTIVE', 0x0002);
define('VOIPUSERNUMBER_DEFAULT', 0x0004);

/**
 * Implements hook_perm().
 */
function voipusernumber_perm() {
  return array(
    'Have VoIP user number',
    'Edit own VoIP user number',
    'Administer VoIP user numbers',
  );
}

/**
 * Implements hook_theme().
 */
function voipusernumber_theme() {
  return array(
    'voipusernumber_settings_page' => array(
      'arguments' => array('content' => NULL),
      'file' => 'sms_user.user.inc',
  
    ),
    'voipusernumber_phone_numbers' => array(
      'arguments' => array('field_name' => NULL, 'delta' => 0, 'node_type' => NULL),
    ),
  );
}
 /**
 * Implementation of hook_schema_alter().
 *
 * @param &$schema Nested array describing the schemas for all modules.
 */
function voipusernumber_schema_alter(&$schema) {
  // Add field to existing schema.
$schema['users']['fields']['source'] = array(
    'type' => 'varchar',
    'unsigned' => TRUE,
    'not null' => TRUE,
    'default' => 'web',
    'description' => t('User Source either from phone or web'),
    );
}

/**
 * Implements hook_menu().
 */
function voipusernumber_menu() {
  $items = array();

  $items['user/%user/edit/voipnumber'] = array(
    'title' => 'Phone number',
    'page callback' => 'voipusernumber_settings_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'voipusernumber_view_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit',
    'file' => 'voipusernumber.user.inc',
  );
  $items['user/%user/edit/voipnumber/add'] = array(
    'title' => 'Add number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipusernumber_settings_add_form', 1),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipusernumber_edit_access',
      // @todo and not if set and no multiple.
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit/voipnumber',
    'file' => 'voipusernumber.user.inc',
  );

  $items['user/%user/edit/voipnumber/%/delete'] = array(
    'title' => 'Delete mobile number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipusernumber_settings_delete_form', 1, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipusernumber_edit_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit/voipnumber',
    'file' => 'voipusernumber.user.inc',
  );
  $items['voipnumber/call'] = array(
    'title' => 'Call',
    'description' => '',
    'page callback' => 'voipusernumber_call',
    'type' => MENU_CALLBACK,
    'access callback' =>'user_access',
  );
   
  $items['voipnumber/get/status'] = array(
    'title' => 'Get Call Status',
    'description' => '',
    'page callback' => 'voipusernumber_get_status',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
  );
   
  $items['voipnumber/hangup'] = array(
    'title' => 'Hangup',
    'description' => '',
    'page callback' => 'voipusernumber_hangup',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
  );

  return $items;
}

/**
 * Menu access callback.
 */
function voipusernumber_view_access($account) {
  return (user_edit_access($account) && user_access('Have VoIP user number'));
}

/**
 * Menu access callback.
 */
function voipusernumber_edit_access($account) {
  global $user;
  return (user_edit_access($account) && $user->uid == $account->uid && user_access('Edit own VoIP user number')) || (user_edit_access($account) && user_access('Administer VoIP user numbers'));
}

/**
 * Implements hook_user().
 */
function voipusernumber_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      return voipusernumber_user_load($account, $category);
    case 'insert':
    case 'update':
      return voipusernumber_user_save($edit, $account, $category);
    case 'view':
      return voipusernumber_user_view($account);
    case 'register':
      return voipusernumber_user_register();
    case 'delete':
      return voipusernumber_user_delete($account->uid);
    case 'validate':
      return;
    case 'login':
      return;
    case 'categories':
      return voipusernumber_user_categories();
  }
}

/**
 * hook_user() for $op = 'load'.
 */
function voipusernumber_user_load(&$account, $category) {
  $account->voipusernumber = array();
  $account->voipusernumber = VoipUserNumber::getNumbersFromUid($account->uid);
}

/**
 * hook_user() for $op = 'insert' || $op = 'update'.
 *
 * Note there is a unique constraint on the number in the table, uniqueness
 * should be checked before adding to the user object.
 *
 * @todo seperate insert, update; keep common together.
 */
function voipusernumber_user_save(&$edit, &$account, $category) {
  if (($category == 'voipnumber' || $category == 'account') && $edit['voipnumber']) {
    $numbers = $edit['voipnumber'];
    db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $account->uid);
    foreach ($numbers as $number) {
      $voipnumber = new VoipUserNumber($number['number'], $account->uid, $number['number_prefix'], $number['status']);
      drupal_write_record('voipusernumber_numbers', $voipnumber);
      $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
    }
    $edit['voipnumber'] = NULL;
  }
  else {
    db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $account->uid);
    foreach ((array) $account->voipnumber as $number) {
      drupal_write_record($number);
    }
  }
}

/**
 * hook_user() for $op = 'view'.
 */
function voipusernumber_user_view(&$account) {
   
}

/**
 * hook_user() for $op = 'register'.
 */
function voipusernumber_user_register() {
}

/**
 * Delete all numbers for a user.
 *
 * Called as hook_user() for $op = 'delete'. Could be seperated. Naming?
 */
function voipusernumber_user_delete($uid) {
  db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $uid);
}

/**
 * Delete individual number for user.
 *
 * @param int $uid
 *   User ID.
 * @param string $number
 *   Number to delete.
 */
function voipusernumber_delete_number($uid, $number) {
  db_query("DELETE FROM {voipusernumber_numbers} WHERE uid = %d AND phone = '%s'", $uid, $number);
}

/**
 * hook_user() for $op = profile.
 */
function voipusernumber_user_categories() {
  return array(
    'voipusernumber' => array(
      'name' => 'voipnumber',
      'title' => t('Phone number'),
      'weight' => 10,
    ),
  );
}

/**
 * Create a new user, by phone number.
 *
 * Could optionally allow username being passed,
 * but then would need to offer a fail for existing
 * username.
 *
 * @param string|int $number
 *   Phone number to create user for.
 * @param array $options
 *   (optional) Keyed array of additional user options.
 *   'pass' => Drupal user password,
 *   'number_status' => VOIPUSERNUMBER_status,
 *   'number_prefix' => VoipNumber type or prexix,
 *   'user_status' => Drupal user status,
 *   'mail' => e-mail address,
 *   'roles' => array of rolse to put user in,
 *   'language' => user language,
 *
 * @return int
 *   User ID.
 */
function voipusernumber_user_create($number, $options = array()) {
  $defaults = array(
    'pass' => user_password(8),
    'number_status' => 0,
    'number_prefix' => '',
    'user_status' => 1,
    // @todo more unique, non example.com dud e-mail.
    'mail' => $number . '@example.com',
    'roles' => ($role = variable_get('voipusernumber_registration_role', NULL)) ? array($role => 1) : NULL,
     // @todo set language to site default?
    'language' => '',
    'source' => 'phone',
  );
  $options += $defaults;

  while (! $uid) {
    $voipnumber = new VoipUserNumber($number, NULL, $number_prefix, $phone_status);
    $account = user_save(NULL, array(
      'name' => variable_get('voipusernumber_registration_username', 'Drupal-') . mt_rand(1, db_result(db_query('SELECT MAX(uid) FROM {users}')) * 10),
      'pass' => $options['pass'],
      'mail' => $options['mail'],
      'roles' => $options['roles'],
      'status' => $options['user_status'],
      'language' => $options['language'],
      'source' => $options['source'],
      'voipnumber' => array(
        $number => array(
          'number' => $number,
          'status' => $options['number_status'],
          'number_prefix' => $options['number_prefix'],
        ),
      ),
    ));
    if ($account) {
      $uid = $account->uid;
    }
  }

  return $uid;
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function voipusernumber_voipscript_get_script_names() {
  return array(
    'voipusernumber_autologin',
    'voipusernumber_logout',
    'voipusernumber_auth',
    'voipusernumber_ask_pin',
  );
}

/**
 * Implements hook_voipscript_load_script().
 */
function voipusernumber_voipscript_load_script($script_name, $params = NULL) {
  switch ($script_name) {
    case 'voipusernumber_autologin':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      if (isset($params['create'])) {
        return _voipusernumber_autologin_script($params['number'], $params['create']);
      }
      else {
        return _voipusernumber_autologin_script($params['number']);
      }
    case 'voipusernumber_logout':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      return _voipusernumber_logout_script();
//    case 'voipusernumber_auth':
//      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
//      return _voipusernumber_auth_script();
    case 'voipusernumber_ask_pin':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      watchdog('voipusernumber',' loadscript has been called @script', array('@script'=>$script));
      return _voipusernumber_ask_pin();
     
  }
}

/**
 * Implements hook_get_voip_numbers().
 *
 * @todo ...
 */
function voipusernumber_get_voip_numbers($id, $type) {
  $numbers = array();
  switch ($type) {
    case 'user':
      $account = user_load($id);
      if (isset($account->sms_user)) {
        $number = $account->sms_user[0]['number'];
        $name = 'SMS Framework (' . $number . ')';
        $type = 'SMS Number';
        $numbers[] = new VoipNumber($number, $name, $type);
      }
      return $numbers;
      break;

    case 'uids':
      $sql = "SELECT uid FROM {sms_user} WHERE number = '" . $id . "'";
      $result = db_query($sql);
      while ($temp = db_fetch_array($result)) {
        if ($temp['uid'] != "") {
          $uids[$temp['uid']] = $temp['uid'];
        }
      }
      return $uids;
      break;
  }
}
/*
 * Check for the pin match 


function _voipusernumber_validate_pin($pin = NULL) {
  $form_pin = variable_get('pin_variable_ask','');   
  if (is_null($pin)) {
    watchdog('voipusernumber', 'Pin number is null.');
    return FALSE;
  }

  if ($pin != $form_pin) {
    watchdog('voipusernumber', 'Invalid Pin. Input: @pin', array('@pin' => $pin), WATCHDOG_NOTICE);
    watchdog('voipusernumber', 'Invalid Pin. Input: @form_pin', array('@form_pin' => $form_pin), WATCHDOG_NOTICE);
    return FALSE;
  }

  watchdog('voipusernumber', 'Pin matches.');
  return TRUE;
}
*/
  function _voipusernumber_writerecord() {
    $form_number= variable_get('form_number','');
    $form_uid= variable_get('form_uid','');
    $voipnumber = new VoipUserNumber($form_number, $form_uid);
    drupal_write_record('voipusernumber_numbers', $voipnumber);
    $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
    watchdog('voipusernumber', 'User data added successfully.');
} 
function voipusernumber_call() {
 global $user;

  if (empty($_GET['phone']) || empty($_GET['field_name'])) {
    return;
  }
 if($_GET['field_name'] == 'user') {
      //User profile
      //Permission checking
//      if (!user_access('Edit own VoIP user number')) {
//        return;
//      }
  $caller_uid = $_GET['delta'];
  $caller = user_load($caller_uid);
//$name = $caller->click2call_user_script_desc;
  $name = 'nitesh';
//$script_name = $caller->click2call_user_script;
  $script_name= 'voipusernumber_ask_pin';
  $caller_name = $caller->name;
  $number=$_GET['phone']; 
  $vars = array('uid' => $user->uid, 'name' => $name, 'number' => $number, 'caller_uid' => $caller_uid);
  $script = VoipScript::loadScript($script_name,$vars);
  print_r(dsm($script));
  if(!empty($script)) {
    watchdog('voipusernumber', "new script $script_name: " . print_r($script, true));
  }
  $call = new VoipCall();
  $call->setDestNumber($number);
  $call->setDestName($user->name);
  $call->setCallerName($caller_name);
  $call->setScript($script);
//  watchdog('voipusernumber', " new call$call: " . print_r($call, true));
  $call->save();
     // Dial the call.
  $result = voip_dial($call);
  if($result) {
  watchdog('voipusernumber','dial call has been made @script', array('@script'=>$script));
  }
   
  // Log call with watchdog
  $type = 'click2call';
  $message = t("New Click2Call message recorded by $user->name to phone $number. See voipcall nid " . $call->getCid());
  watchdog($type, $message);
  
  $rc = drupal_json(array('call_nid' => $call->getCid()));
  return $rc;
  exit();
    }
}
function voipusernumber_get_status() {
  global $user;
    $call_nid=$_GET['call_nid'];
    $call = VoipCall::load($call_nid);
    //Check for status only if call is finished
    if ($call->isHangup()==TRUE) {
    if ($call->getCallStatus() != VoipCall::COMPLETED) {
      if ($call->getCallStatus() == VoipCall::ERROR) {
        $failed_message='<div class="error">' . $call->getErrorMessage() . '</div>';
      }
      elseif ($call->getCallStatus()=='to_hangup' || $call->getCallStatus() == VoipCall::CANCELED) {
        //We display message for all statuses except hangup
        $failed_message='<div class="messages status">' . $call->getCallStatusDescription() . '</div>';
      }
      else {
        $failed_message='<div class="error">' . $call->getCallStatusDescription() . '</div>';
      }
      $rc = drupal_json(array('status' => 'failed', 'message' => $failed_message));
      return $rc;
      exit();
    }
#Else:
    $message='<div class="messages status">' . $call->getCallStatusDescription() . '</div>';
    $rc = drupal_json(array('status' => 'success' , 'message' => $message));
    return $rc;
    exit();
  }
  else {
   $rc = drupal_json(array('status' => 'calling'));
   return $rc;
  }
  exit();
}
function voipusernumber_hangup() {
    $voipcall_nid = $_GET['call_nid'];
  $call = VoipCall::load($voipcall_nid);
  $status = voip_hangup($call);
  $rc = drupal_json(array('status' => $status));
  return $rc;
  exit();
} 
/*Retrieve and theme phone numbers selection*/
function theme_voipusernumber_phone_numbers($field_name, $delta, $content_type) {
  global $user;
  $field_settings=content_fields($field_name, $content_type);
  if (empty($field_settings)) {
    $op = variable_get('click2call_number', array('type'));
  }
  else {
    $op = $field_settings['click2call_number'];
  }  
  foreach ($op as $key => $call_option) {
    if ($call_option===0) {
      unset($op[$key]);
    }
  }
  $num=count($op);
  if ($num==1 || $user->uid==0) {
    //If only one choice is available or user is anonymous then make the option preselected
    $checked='checked="checked"';
  }
  foreach ($op as $call_option) {
    switch ($call_option) {
      case 'default':
        if (module_exists('voipnumber')) {
          $phone = VoipNumber::getDefaultNumberFromUid();
          if (empty($phone)) {      
            if ($num==2) {
              //If only 2 choices are available then make the other selected
              $checked='checked="checked"';
            }
          }
          else {
            $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="' . $phone->getNumber() . '" checked="checked"/>Default (' . $phone->getNumber() . ')<br/>';
          }
        }
        break;

      case 'type':
        $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="type" ' . $checked . '/><input type="text" id="click2call-' . $field_name . '-' . $delta . '-type-phone" class="click2call-type"/><br/>';
        break;

      case 'voipnumber':
        if (module_exists('voipnumber')) {
          $numbers = VoipNumber::getNumbersFromUid();
          //Numbers could be empty, check.
          if (empty($numbers)) {
            continue;
          }
          $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="voipnumber" ' . $checked . '/>';
          $option .= '<select class="click2call-voipnumber" id="click2call-' . $field_name . '-' . $delta . '-select">';
          foreach ($numbers as $number) {
            $option .= "<option value='".$number->getNumber()."'> ".$number->getName()." </option>";
          }
          $option .= '</select><br/>';
        }
        break;
    }
  }
  $output .= '<div class="click2call-' . $field_name . '-' . $delta . '-phone">' . $option . '</div>';
  return $output;
}