<?php

/**
 * @file
 *   Drupal user and Drupal VoIP module integration.
 */

define('VOIPUSERNUMBER_CONFIRMED', 0x0001);
define('VOIPUSERNUMBER_ACTIVE', 0x0002);
define('VOIPUSERNUMBER_DEFAULT', 0x0004);

/**
 * Implements hook_perm().
 */
function voipusernumber_perm() {
  return array(
    'Have VoIP user number',
    'Edit own VoIP user number',
    'Administer VoIP user numbers',
  );
}

/**
 * Implements hook_theme().
 */
function voipusernumber_theme() {
  return array(
    'voipusernumber_settings_page' => array(
      'arguments' => array('content' => NULL),
      'file' => 'sms_user.user.inc',
  
    ),
    'voipusernumber_phone_numbers' => array(
      'arguments' => array('field_name' => NULL, 'delta' => 0, 'node_type' => NULL),
    ),
  );
}
 
 /**
 * Implements hook_menu().
 */
function voipusernumber_menu() {
  $items = array();

  $items['user/%user/edit/voipnumber'] = array(
    'title' => 'Phone number',
    'page callback' => 'voipusernumber_settings_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'voipusernumber_view_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit',
    'file' => 'voipusernumber.user.inc',
  );
  $items['user/%user/edit/voipnumber/add'] = array(
    'title' => 'Add number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipusernumber_settings_add_form', 1),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipusernumber_edit_access',
      // @todo and not if set and no multiple.
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit/voipnumber',
    'file' => 'voipusernumber.user.inc',
  );

  $items['user/%user/edit/voipnumber/%/delete'] = array(
    'title' => 'Delete mobile number',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipusernumber_settings_delete_form', 1, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'voipusernumber_edit_access',
    'access arguments' => array(1),
    'tab_parent' => 'user/%/edit/voipnumber',
    'file' => 'voipusernumber.user.inc',
  );
  $items['voipnumber/call'] = array(
    'title' => 'Call',
    'page callback' => 'voipusernumber_call',
    'type' => MENU_CALLBACK,
    'access arguments' => array('Edit own VoIP user number'),
  );
   
  $items['voipnumber/get/status'] = array(
    'title' => 'Get Call Status',
    'page callback' => 'voipusernumber_get_status',
    'type' => MENU_CALLBACK,
    'access arguments' => array('Edit own VoIP user number'),
  );
   
  $items['voipnumber/hangup'] = array(
    'title' => 'Hangup',
    'page callback' => 'voipusernumber_hangup',
    'type' => MENU_CALLBACK,
   'access arguments' => array('Edit own VoIP user number'),
  );
  return $items;
}

/**
 * Menu access callback.
 */
function voipusernumber_view_access($account) {
  return (user_edit_access($account) && user_access('Have VoIP user number'));
}

/**
 * Menu access callback.
 */
function voipusernumber_edit_access($account) {
  global $user;
  return (user_edit_access($account) && $user->uid == $account->uid && user_access('Edit own VoIP user number')) || (user_edit_access($account) && user_access('Administer VoIP user numbers'));
}

/**
 * Implements hook_user().
 */
function voipusernumber_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      return voipusernumber_user_load($account, $category);
    case 'insert':
    case 'update':
      return voipusernumber_user_save($edit, $account, $category);
    case 'view':
      return voipusernumber_user_view($account);
    case 'register':
      return voipusernumber_user_register();
    case 'delete':
      return voipusernumber_user_delete($account->uid);
    case 'validate':
      return;
    case 'login':
      return;
    case 'categories':
      return voipusernumber_user_categories();
  }
}

/**
 * hook_user() for $op = 'load'.
 */
function voipusernumber_user_load(&$account, $category) {
  $account->voipusernumber = array();
  $account->voipusernumber = VoipUserNumber::getNumbersFromUid($account->uid);
}

/**
 * hook_user() for $op = 'insert' || $op = 'update'.
 *
 * Note there is a unique constraint on the number in the table, uniqueness
 * should be checked before adding to the user object.
 *
 * @todo seperate insert, update; keep common together.
 */
function voipusernumber_user_save(&$edit, &$account, $category) {
  /**
  if (($category == 'voipnumber' || $category == 'account') && $edit['voipnumber']) {
    $numbers = $edit['voipnumber'];
    db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $account->uid);
    foreach ($numbers as $number) {
      $voipnumber = new VoipUserNumber($number['number'], $account->uid, $number['number_prefix'], $number['status']);
      drupal_write_record('voipusernumber_numbers', $voipnumber);
      $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
    }
    $edit['voipnumber'] = NULL;
  }
  else {
    db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $account->uid);
    foreach ((array) $account->voipnumber as $number) {
      drupal_write_record($number);
    }
  }
  **/
}

/**
 * hook_user() for $op = 'view'.
 */
function voipusernumber_user_view(&$account) {
   
}

/**
 * hook_user() for $op = 'register'.
 */
function voipusernumber_user_register() {
}

/**
 * Delete all numbers for a user.
 *
 * Called as hook_user() for $op = 'delete'. Could be seperated. Naming?
 */
function voipusernumber_user_delete($uid) {
  db_query('DELETE FROM {voipusernumber_numbers} WHERE uid = %d', $uid);
}

/**
 * Delete individual number for user.
 *
 * @param int $uid
 *   User ID.
 * @param string $number
 *   Number to delete.
 */
function voipusernumber_delete_number($uid, $number) {
  db_query("DELETE FROM {voipusernumber_numbers} WHERE uid = %d AND phone = '%s'", $uid, $number);
}

/**
 * hook_user() for $op = profile.
 */
function voipusernumber_user_categories() {
  return array(
    'voipusernumber' => array(
      'name' => 'voipnumber',
      'title' => t('Phone number'),
      'weight' => 10,
    ),
  );
}

/**
 * Create a new user, by phone number.
 *
 * Could optionally allow username being passed,
 * but then would need to offer a fail for existing
 * username.
 *
 * @param string|int $number
 *   Phone number to create user for.
 * @param array $options
 *   (optional) Keyed array of additional user options.
 *   'pass' => Drupal user password,
 *   'number_status' => VOIPUSERNUMBER_status,
 *   'number_prefix' => VoipNumber type or prexix,
 *   'user_status' => Drupal user status,
 *   'mail' => e-mail address,
 *   'roles' => array of rolse to put user in,
 *   'language' => user language,
 *
 * @return int
 *   User ID.
 */
function voipusernumber_user_create($number, $options = array()) {
  $defaults = array(
    'pass' => user_password(8),
    'number_status' => 0,
    'number_prefix' => '',
    'user_status' => 1,
    // @todo more unique, non example.com dud e-mail.
    'mail' => $number . '@example.com',
    'roles' => ($role = variable_get('voipusernumber_registration_role', NULL)) ? array($role => 1) : NULL,
     // @todo set language to site default?
    'language' => '',
  );
  $options += $defaults;

  while (! $uid) {
    $voipnumber = new VoipUserNumber($number, NULL, $number_prefix, $phone_status);
    $account = user_save(NULL, array(
      'name' => variable_get('voipusernumber_registration_username', 'Drupal-') . mt_rand(1, db_result(db_query('SELECT MAX(uid) FROM {users}')) * 10),
      'pass' => $options['pass'],
      'mail' => $options['mail'],
      'roles' => $options['roles'],
      'status' => $options['user_status'],
      'language' => $options['language'],
      'voipnumber' => array(
        $number => array(
          'number' => $number,
          'status' => $options['number_status'],
          'number_prefix' => $options['number_prefix'],
          'source'=> '',
        ),
      ),
    ));
    if ($account) {
      $uid = $account->uid;
    }
  }

  return $uid;
}

/**
 * Implements hook_voipscript_get_script_names().
 */
function voipusernumber_voipscript_get_script_names() {
  return array(
    'voipusernumber_autologin',
    'voipusernumber_logout',
    'voipusernumber_ask_pin',
  );
}

/**
 * Implements hook_voipscript_load_script().
 */
function voipusernumber_voipscript_load_script($script_name, $params = NULL) {
  switch ($script_name) {
    case 'voipusernumber_autologin':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      if (isset($params['create'])) {
        return _voipusernumber_autologin_script($params['number'], $params['create']);
      }
      else {
        return _voipusernumber_autologin_script($params['number']);
      }
    case 'voipusernumber_logout':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      return _voipusernumber_logout_script();
    case 'voipusernumber_ask_pin':
      module_load_include('inc', 'voipusernumber', 'voipusernumber.script');
      return _voipusernumber_ask_pin($params['number'],$params['uid']);
     }
}

/**
 * Implements hook_get_voip_numbers().
 *
 * @todo ...
 */
function voipusernumber_get_voip_numbers($id, $type) {
  $numbers = array();
  switch ($type) {
    case 'user':
      $account = user_load($id);
      if (isset($account->sms_user)) {
        $number = $account->sms_user[0]['number'];
        $name = 'SMS Framework (' . $number . ')';
        $type = 'SMS Number';
        $numbers[] = new VoipNumber($number, $name, $type);
      }
      return $numbers;
      break;

    case 'uids':
      $sql = "SELECT uid FROM {sms_user} WHERE number = '" . $id . "'";
      $result = db_query($sql);
      while ($temp = db_fetch_array($result)) {
        if ($temp['uid'] != "") {
          $uids[$temp['uid']] = $temp['uid'];
        }
      }
      return $uids;
      break;
  }
}

function voipusernumber_validate(){
  global $user;
$error = '';
$number=$_GET['phone'];
  $uid=VoipUserNumber::getUidFromNumber($number);
  // Basic VoIPNumber validation.
  _voipnumber_valid_int_phone_number($number, $error);
  if (! empty($error)) {
    return FALSE;
    
  }
  // Unique validation.
  elseif ($uid==$user->uid) {
    watchdog('voipusernumber','phone exist @number',array('@number'=>$number),watchdog_error);
     return FALSE;
    
  }
  else {
    watchdog('voipusernumber','validation pass @number',array('@number'=>$number),watchdog_error);
  return TRUE;
  }  
}
 function voipusernumber_writerecord($number,$uid) { 
 $result = db_query('select ifnull(uid,0) uid FROM {voipusernumber_numbers} where phone=%s and source=%d',$number,0);
    while ($record = db_fetch_object($result)) {
      $uidtomerge = $record->uid;
    }
    if($uidtomerge != '') {
    voipusernumber_do_user_merge($uid,$uidtomerge);
    watchdog('voipusernumber', 'User merge has been done successfully.');
    $voipnumber = new VoipUserNumber($number, $uid,1,1,1);
    drupal_write_record('voipusernumber_numbers', $voipnumber);
    $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
    }
    else {
    $sql= db_query('select uid from {voipusernumber_numbers} where phone=%d and source=%d and uid !=%d',$number,1,$uid);
    while ($record = db_fetch_object($result)) {
      $uidtodelete = $record->uid;
    }  
      if ($uidtodelete != ''){
      voipusernumber_delete_number($number,$uidtodelete);
      }
    $voipnumber = new VoipUserNumber($number, $uid,1,1,1);
    drupal_write_record('voipusernumber_numbers', $voipnumber);
    $account->voipnumber[$voipnumber->getNumber()] = $voipnumber;
         }
}

function voipusernumber_do_user_merge($uid, $uidtomerge) {
    module_invoke_all('user_merge', $uidtomerge, $uid);
}

/**
 * Implement hook_usermerge_merge_users().
 */
function voipusernumber_user_merge($uidtomerge, $uid) {
  // Comment: change the uid to the new one.
  db_query('UPDATE {comments} SET uid = %d where uid = %d', $uid->uid, $uidtomerge->uid);

  // Node: change uid of node and revisions to the new one.
  db_query('UPDATE {node} SET uid = %d where uid = %d', $uid->uid, $uidtomerge->uid);
  db_query('UPDATE {node_revisions} SET uid = %d where uid = %d', $uid->uid, $uidtomerge->uid);

  //Update roles.
  $merged_roles = $uid->roles + $uidtomerge->roles;

  // First, remove all roles from the user to keep to prevent duplicate key errors.
  db_query("DELETE FROM {users_roles} WHERE uid = %d", $uid->uid);
  // Then add them on to the user to keep.
  foreach (array_keys($merged_roles) as $rid) {
    if (!in_array($rid, array(DRUPAL_ANONYMOUS_RID, DRUPAL_AUTHENTICATED_RID))){
      db_query('INSERT INTO {users_roles} (uid, rid) VALUES (%d, %d)', $uid->uid, $rid);
    }
  }
  // Block the old user.
  user_block_user_action($uidtomerge);
}

/**
 * Implement hook_usermerge_merge_users() on behalf of og.
 */
function og_user_merge($uidtomerge, $uid) {
  // Get groups kept-user is not a member of but blocked-user is.
  $result = db_query("SELECT nid FROM {og_uid} WHERE uid = %d AND nid NOT IN (SELECT nid FROM {og_uid} WHERE uid = %d)", $uidtomerge->uid, $uid->uid);
  while ($record = db_fetch_array($result)) {
    $groups[] = $record['nid'];
  }
  if (!empty($groups)) {
    // Update old user's groups to kept-user if kept-user is not already a member.
    db_query("UPDATE {og_uid} SET uid = %d WHERE uid = %d AND nid IN (%s)", $uid->uid, $uidtomerge->uid, implode(',', $groups));
  }
  // Set blocked-user to inactive.
  db_query("UPDATE {og_uid} SET is_active = 0 WHERE uid = %d", $uidtomerge->uid);
}

/**
 * Implement hook_usermerge_merge_users() on behalf of notifications.
 */
function notifications_usermerge_merge_users($uidtomerge, $uid) {
  // Get blocked-user's notifications.
  $blocked = array();
  $result = db_query("SELECT sid FROM {notifications} WHERE uid = %d". $uidtomerge->uid);
  while ($record = db_fetch_array($result)) {
    $blocked[] = $record['sid'];
  }
  if (!empty($blocked)) {
    // Delete notification settings.
    db_query("DELETE FROM {notifications} WHERE uid = %d", $uidtomerge->uid);
    // Delete fields of blocked-user's notifications settings, they aren't used.
    db_query("DELETE FROM {notifications_fields} WHERE sid IN (%s)", implode(',', $blocked));
  }
  // Delete notifications in the queue for blocked-user.
  db_query("DELETE FROM {notifications_queue} WHERE uid = %d", $uidtomerge->uid);
}
function voipusernumber_call() {
 global $user;
 $val= voipusernumber_validate();
 if($val == FALSE) { 
 return ;
 }
  if (empty($_GET['phone']) || empty($_GET['field_name'])) {
  return;
  }
 if($_GET['field_name'] == 'user') {
  variable_set('form_number', $_GET['phone']);
  $caller_uid = $_GET['delta'];
  $caller = user_load($caller_uid);
  $name = $caller->name;
  $script_name= 'voipusernumber_ask_pin';
  $caller_name = $caller->name;
  $number=$_GET['phone'];
  $uid= $user->uid;
  $vars = array('uid' => $user->uid, 'name' => $name, 'number' => $number, 'caller_uid' => $caller_uid);
  $script = VoipScript::loadScript($script_name,$vars);
  
  $call = new VoipCall();
  $call->setDestNumber($number);
  $call->setDestName($user->name);
  $call->setCallerName($caller_name);
  $call->setScript($script);
  $call->save();
     // Dial the call.
  $result = voip_dial($call);
  // Log call with watchdog
  $type = 'voipusernumber';
  $message = t("New Call had been recorded by $user->name to phone $number. See voipcall nid " . $call->getCid());
  watchdog($type, $message);
  
  $rc = drupal_json(array('call_nid' =>$call->getCid()));
  return $rc;
  exit();
    }
}
function voipusernumber_get_status() {
  global $user;
    $call_nid=$_GET['call_nid'];
    $call = VoipCall::load($call_nid);
    //Check for status only if call is finished
    if ($call->isHangup()==TRUE) {
    if ($call->getCallStatus() != VoipCall::COMPLETED) {
      if ($call->getCallStatus() == VoipCall::ERROR) {
        $failed_message='<div class="error">' . $call->getErrorMessage() . '</div>';
      }
      elseif ($call->getCallStatus()=='to_hangup' || $call->getCallStatus() == VoipCall::CANCELED) {
        //We display message for all statuses except hangup
        $failed_message='<div class="messages status">' . $call->getCallStatusDescription() . '</div>';
      }
      else {
        $failed_message='<div class="error">' . $call->getCallStatusDescription() . '</div>';
      }
      $rc = drupal_json(array('status' => 'failed', 'message' => $failed_message));
      return $rc;
      exit();
    }
#Else:
    $message='<div class="messages status">' . $call->getCallStatusDescription() . '</div>';
    $rc = drupal_json(array('status' => 'success' , 'message' => $message));
    return $rc;
    exit();
  }
  else {
   $rc = drupal_json(array('status' => 'calling'));
   return $rc;
  }
  exit();
}
function voipusernumber_hangup() {
  $voipcall_nid = $_GET['call_nid'];
  $call = VoipCall::load($voipcall_nid);
  $status = voip_hangup($call);
  $rc = drupal_json(array('status' => $status));
  return $rc;
  exit();
} 
/*Retrieve and theme phone numbers selection*/
function theme_voipusernumber_phone_numbers($field_name, $delta, $content_type) {
  global $user;
  $field_settings=content_fields($field_name, $content_type);
  if (empty($field_settings)) {
    $op = variable_get('click2call_number', array('type'));
  }
  else {
    $op = $field_settings['click2call_number'];
  }  
  foreach ($op as $key => $call_option) {
    if ($call_option===0) {
      unset($op[$key]);
    }
  }
  $num=count($op);
  if ($num==1 || $user->uid==0) {
    //If only one choice is available or user is anonymous then make the option preselected
    $checked='checked="checked"';
  }
  foreach ($op as $call_option) {
    switch ($call_option) {
      case 'default':
        if (module_exists('voipnumber')) {
          $phone = VoipNumber::getDefaultNumberFromUid();
          if (empty($phone)) {      
            if ($num==2) {
              //If only 2 choices are available then make the other selected
              $checked='checked="checked"';
            }
          }
          else {
            $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="' . $phone->getNumber() . '" checked="checked"/>Default (' . $phone->getNumber() . ')<br/>';
          }
        }
        break;

      case 'type':
        $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="type" ' . $checked . '/><input type="text" id="click2call-' . $field_name . '-' . $delta . '-type-phone" class="click2call-type"/><br/>';
        break;

      case 'voipnumber':
        if (module_exists('voipnumber')) {
          $numbers = VoipNumber::getNumbersFromUid();
          //Numbers could be empty, check.
          if (empty($numbers)) {
            continue;
          }
          $option .= '<input type="radio" name="click2call-' . $field_name . '-' . $delta . '-phone" value="voipnumber" ' . $checked . '/>';
          $option .= '<select class="click2call-voipnumber" id="click2call-' . $field_name . '-' . $delta . '-select">';
          foreach ($numbers as $number) {
            $option .= "<option value='".$number->getNumber()."'> ".$number->getName()." </option>";
          }
          $option .= '</select><br/>';
        }
        break;
    }
  }
  $output .= '<div class="click2call-' . $field_name . '-' . $delta . '-phone">' . $option . '</div>';
  return $output;
}